### ISSUE TITLE
észrevételek

### ISSUE THREAD

**Issue by gomszab** [nemethkoppany/dolgozat_ropi_megoldasok#1]
https://github.com/nemethkoppany/dolgozat_ropi_megoldasok/blob/20769220c95f38f4baf2ce7ad41c10b8ceac2711/ropdoga.txt#L13
A kérdésre adott válasz helyes, én a git commit -m "" parancs kiadásának hiányára gondoltam. Mivel a kérdések feleletválasztósak lesznek, szerintem ezt adom meg majd helyes válasznak.

https://github.com/nemethkoppany/dolgozat_ropi_megoldasok/blob/20769220c95f38f4baf2ce7ad41c10b8ceac2711/ropdoga.txt#L19
A válasz helytelen. A saját accountra történő másolást a "Fork" gombbal tudom létrehozni, a clone-al a saját gépemre töltöm le a repositoryt.

https://github.com/nemethkoppany/dolgozat_ropi_megoldasok/blob/20769220c95f38f4baf2ce7ad41c10b8ceac2711/ropdoga.txt#L23
A kis-nagybetű különbség nem tudom fontos-e itt ebben az esetben. Ez csak kukacoskodás, nyilván élesben úgyis észreveszi az ember, ha nem megy

https://github.com/nemethkoppany/dolgozat_ropi_megoldasok/blob/20769220c95f38f4baf2ce7ad41c10b8ceac2711/ropdoga.txt#L26
A válasz jó, el is fogadnám, ha nem lenne ott a kérdésben, hogy "új branchre" a -b flag is kell ilyenkor. Ha nem szeretnénk új branchet létrehozni, akkor a te válaszod is helyes.

https://github.com/nemethkoppany/dolgozat_ropi_megoldasok/blob/20769220c95f38f4baf2ce7ad41c10b8ceac2711/ropdoga.txt#L67
Reménykedem benne, hogy kipróbáltad a css-t, mikor a választ beírtad (és nem vagy szintévesztő). Nálam nem ezt mutatja (:

https://github.com/nemethkoppany/dolgozat_ropi_megoldasok/blob/20769220c95f38f4baf2ce7ad41c10b8ceac2711/ropdoga.txt#L92
Az esélyed megvolt eltalálni, de sajnos ez mellé ment. A szabály: Mindig a szigorúbb szabály van érvénybe. Ha belegondolsz, akkor a table tr az a táblázat soraira vonatkozik, aminél szigorúbb ha a táblázat celláira definiálunk szabályt. Ezen nem módosít az sem, hogy nth-child(2n) van, mert a tr szinten vagyunk, nem a td-n

https://github.com/nemethkoppany/dolgozat_ropi_megoldasok/blob/20769220c95f38f4baf2ce7ad41c10b8ceac2711/ropdoga.txt#L194
Az esélyed megvolt eltalálni. Szabály: kihez szeretnék hozzáadni? A sorhoz. Mit szeretnék hozzáadni? Egy cellát. Amihez hozzá akarunk adni, annak kell az appendchildját meghívni és paraméterként adjuk meg, hogy kit akarunk hozzáadni. 

https://github.com/nemethkoppany/dolgozat_ropi_megoldasok/blob/20769220c95f38f4baf2ce7ad41c10b8ceac2711/ropdoga.txt#L201
Ugyanazt írhatnám mint az elözőnél. De érdekes, hogy a table-nél még tudod, hogy a tr-t adjuk hozzá, mert a table a tr apukája/anyukája, de a td-nél már fordítva gondolod. táblázat html kódját képzeld el - és ha jól van formázva - akkor látod ki kinek az szülője a behúzások alapján. Értelemszerűen a nyitó és zárótagek közötti részben csak a gyermek lehet a tag-jeivel.

**Comment by nemethkoppany** [comment]
Kijavítottam a hibákat, viszont meg szeretném kérdezni, hogy a 201-es sorban lévő miért nem helyes? Először mindig  az van amihez hozzá akarom adni és az appendChild zárójelébe megy az amit hozzá szeretnék adni, nem? 

Minden mást kijavítottam és feltöltöttem a repoba.

**Comment by gomszab** [comment]
Rosszúl jelöltem ki. 
https://github.com/nemethkoppany/dolgozat_ropi_megoldasok/blob/20769220c95f38f4baf2ce7ad41c10b8ceac2711/ropdoga.txt#L200-L210
Ha megnézed a table-nél jó a sorrend, de a td_1 és a td_2-nél felcserélted. mert azokat a tr-hez kell appendChildolni, nem pedig fordítva.

**Comment by nemethkoppany** [comment]
Ja igen, látom. Azokat is kijavítottam.
